### PR TITLE
Gradient support

### PR DESCRIPTION
**Pull request by Dorokhov**
These changes and [the fix in native API ](https://github.com/tensorflow/tensorflow/commit/d016cb020583b1ecbc260c1492e347c2731b1c29) resolves issue #25 
Now, add gradients works correctly

The test will fail until a new version of TensorFlowSharp with updated native libraries is released.

### CODE REVIEW

**Comment by cesarsouza** [comment]
When can we have a new (pre-)release with this? 👍

**Comment by migueldeicaza** [comment]
Apologies, I have been very busy in the last couple of weeks, but I am back, should be able to get a release in a day or two (as soon as I wrap up Stranger Things :-)

**Comment by cesarsouza** [comment]
Guess we are in the same boat w.r.t Stranger Things ;-)

Thanks Miguel!

**Comment by migueldeicaza** [comment]
Here is the nuget for 1.4.0-pre1:

https://www.nuget.org/packages/TensorFlowSharp/1.4.0-pre1

**Pull request merged**
