### PR TITLE
[WIP] Switch to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by onovotny**
This is the beginning of .NET Standard support for this library. Due to several overloads used, I wasn't able to get it to compile with .NET Standard 1.6 or lower without code changes (which may be possible). The library does compile as-is with .NET Standard 2.0 (yay!).

I did run into an issue with the F# test project not being able to reference the .NET Standard 2.0 class library, so that needs to be resolved first. Not sure what the current status of this is but someone on the F# team should probably weigh in.

### CODE REVIEW

**Comment by dsyme** [comment]
@onovotny Was the problem with using Visual Studio to reference the .NET Standard 2.0 library?  DId you try a direct file reference (not project reference) to the generated DLL? thanks

**Comment by onovotny** [comment]
@dsyme With the p2p ref, I see the following warnings in VS 

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		A reference to library 'TensorFlowSharp' cannot be added. This project targets a different framework (.NETStandard) from the current project (.NETFramework).	TensorFlowSharp.Tests		0	
Warning		A reference to library 'TensorFlowSharp' cannot be added. This project targets a different framework (.NETStandard) from the current project (.NETFramework).	FSharpExampleInceptionInference		0	
Warning		A reference to library 'TensorFlowSharp' cannot be added. This project targets a different framework (.NETStandard) from the current project (.NETFramework).	ImageCompression		0	
```
If I build the test project, I see this:

```
2>
2>C:\dev\TensorFlowSharp\tests\TensorFlowSharp.Tests\ArithmeticOperationTests.fs(15,17): error FS1108: The type 'Object' is required here and is unavailable. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
2>C:\dev\TensorFlowSharp\tests\TensorFlowSharp.Tests\ArithmeticOperationTests.fs(16,17): error FS1108: The type 'Object' is required here and is unavailable. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
2>C:\dev\TensorFlowSharp\tests\TensorFlowSharp.Tests\ArithmeticOperationTests.fs(18,17): error FS1108: The type 'Object' is required here and is unavailable. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
2>C:\dev\TensorFlowSharp\tests\TensorFlowSharp.Tests\ArithmeticOperationTests.fs(22,13): error FS1108: The type 'Object' is required here and is unavailable. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
2>C:\dev\TensorFlowSharp\tests\TensorFlowSharp.Tests\ArithmeticOperationTests.fs(26,25): error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints
2>C:\dev\TensorFlowSharp\tests\TensorFlowSharp.Tests\ArithmeticOperationTests.fs(27,24): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
2>C:\dev\TensorFlowSharp\tests\TensorFlowSharp.Tests\ArithmeticOperationTests.fs(27,24): error FS0008: This runtime coercion or type test from type    'a     to     float32    involves an indeterminate type based on information prior to this program point. Runtime type tests are not allowed on some types. Further type annotations are needed.
2>C:\dev\TensorFlowSharp\tests\TensorFlowSharp.Tests\ArithmeticOperationTests.fs(13,13): error FS1108: The type 'Object' is required here and is unavailable. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
2>Target "_CheckForCompileOutputs" in file "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets" from project "C:\dev\TensorFlowSharp\tests\TensorFlowSharp.Tests\TensorFlowSharp.Tests.fsproj" (target "_CleanGetCurrentAndPriorFileWrites" depends on it):
2>Target "_CleanGetCurrentAndPriorFileWrites" in file "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets" from project "C:\dev\TensorFlowSharp\tests\TensorFlowSharp.Tests\TensorFlowSharp.Tests.fsproj" (target "_CleanRecordFileWrites" depends on it):
2>Target "_CleanRecordFileWrites" in file "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets" from project "C:\dev\TensorFlowSharp\tests\TensorFlowSharp.Tests\TensorFlowSharp.Tests.fsproj" (target "CoreBuild" depends on it):
2>Done building project "TensorFlowSharp.Tests.fsproj" -- FAILED.
2>
2>Build FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
Adding the `NETStandard.Library` package `2.0.0-preview1-25301-01` doesn't help either.

**Comment by onovotny** [comment]
@dsyme One update: Looks like the right meta-package is `NETStandard.Library.NETFramework`. So added that and get fewer errors, just one now:

```
2>FSC: error FS1108: The type 'Object' is required here and is unavailable. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
2>C:\dev\TensorFlowSharp\tests\TensorFlowSharp.Tests\ArithmeticOperationTests.fs(29,9): error FS1109: A reference to the type 'System.Object' in assembly 'System.Runtime' was found, but the type could not be found in that assembly
```

**Comment by dsyme** [comment]
@onovotny That bug is fixed in Microsoft/visualfsharp https://github.com/Microsoft/visualfsharp/pull/3215.  

They are still working on which releases this will be in.

**Comment by L0ndra** [comment]
https://www.visualstudio.com/en-us/news/releasenotes/vs2017-Preview-relnotes#15.3.26621.02
"F# Support: You can use the .NET CLI to create .NET Core console applications and .NET Core /.NET Standard class libraries in F#." Posible that problem with reference was solved

**Comment by migueldeicaza** [comment]
Alternative patch taking place here:

https://github.com/migueldeicaza/TensorFlowSharp/pull/188

**Comment by migueldeicaza** [comment]
Done, with an alternative approach

**Pull request closed without merging**
