### PR TITLE
update to TF 1.14

### PR DESCRIPTION
**Pull request by kevmal**
Generate Operations.g.cs for TF 1.14. With #448 all tests pass.

### CODE REVIEW

**Comment by domtheluck** [comment]
I'm really looking to have 1.14 support. Any plans to merge this pull request?

**Comment by lkuich** [comment]
Many thanks @kevmal! I was in need of TF 1.14 support for a project of mine. Forked/merged your changes and made a package available if anyone's in need (@domtheluck):
https://www.nuget.org/packages/Coach-ML.TensorFlowSharp
https://github.com/coach-ml/TensorFlowSharp/tree/release/1.14.0

**Comment by domtheluck** [comment]
Thanks a lot :)!

**Comment by turowicz** [comment]
@domtheluck @lkuich What about the failing tests?

**Comment by lkuich** [comment]
@turowicz As per the original comment, apparently tests pass with https://github.com/migueldeicaza/TensorFlowSharp/pull/448 merged, which I see it now has, perhaps this build needs to be re-run.

My tests pass locally with both changes merged in.

**Comment by turowicz** [comment]
thanks for the information @lkuich

**Comment by kevmal** [comment]
Merged with master and updated to fix tests. `CurrentIteration : TFOutput` was added to the `Optimizer` class. The newly added Adam optimizer relies on the current iteration but reading the variable directly is unpredictable. `CurrentIteration` is the `Iteration` variable dependent of the op that increments the iteration. Maybe there's really no need to expose both the Varriable (`Iteration`) and the output after iteration? Probably just confuses things, maybe `Iteration` should just simply by the output after increment.

The new Adam tests now pass though there is the potential issue of the unpredictability of when `W.Read` and `b.Read` takes place. Could be either before or after the optimizer update. The adam tests assumes the reads will happen before.

**Comment by migueldeicaza** [comment]
I made a 1.15.0-pre2 release, that should have everything in place.

**Pull request closed without merging**
