### PR TITLE
Object Detection Example ReadMe

### PR DESCRIPTION
**Pull request by Dorokhov**
1. Added shell scripts to run the object detection example on Windows and Mac OS simply. Scripts download trained model, .pbtxt file and run example against the image under the test_images folder.
2. Added README file with a description of the example

### CODE REVIEW

**Comment by migueldeicaza** [comment]
I wonder if we should have a convenience api that the samples can use that download three models instead of us having to maintain two sets of runner scripts?

**Comment by Dorokhov** [comment]
That's a good point, I like it and added appropriate changes

**Comment by migueldeicaza** [comment]
Another -hopefully- small request.   Instead of using SharpZipLib, could we use .NET's built in Zip support from System.IO.Compression, there is a class ZipFile that can do that.

**Comment by Dorokhov** [comment]
ZipFile doesn't work with *.tar.gz archives that's why I used SharpZipLib

**Comment by migueldeicaza** [comment]
Oh :-)

**Pull request merged**
