### PR TITLE
Move to .NET Standard 2

### PR DESCRIPTION
**Pull request by migueldeicaza**
First attempt, is it this easy?

### CODE REVIEW

**Comment by rdthompson2020** [comment]
Since TensorFlowSharp is being used as "Experimental" for Unity ML-Agents, I was wondering if TensorFlowSharp is intented to be compatible with Mono 4.4, C# 4 and .NET 3.5. Obviously with the Reinforcement Learning this is a big growth area (Supporting TensorFlow in Unity). How might it also support TensorFlow Lite on iOS and Android?

**Comment by migueldeicaza** [comment]
I have not looked into TensorFlowSharp lite yet, it is on my todo list.

**Comment by migueldeicaza** [comment]
I suspect the reason this is breaking is because Travis needs to install .NET Core 2 in addition to Mono at build time.

**Comment by Dorokhov** [comment]
hi @migueldeicaza , I managed to move to net standard: https://github.com/migueldeicaza/TensorFlowSharp/pull/193
Please, either use travis config from my PR or merge my changes. Thanks.

**Comment by migueldeicaza** [comment]
Thanks for the pull request!   I am taking the bits from your .travis file, and the Makefile.

I do not want to move to netcoreapp2.0 though, but there are other changes there that I would not mind bringing.

**Comment by migueldeicaza** [comment]
My next failure is produced by F# which does not seem to like the .NET Standard library:

```
FSC : error FS1108: The type 'Object' is required here and is unavailable. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [/Users/travis/build/migueldeicaza/TensorFlowSharp/tests/TensorFlowSharp.Tests/TensorFlowSharp.Tests.fsproj]
  
/Users/travis/build/migueldeicaza/TensorFlowSharp/tests/TensorFlowSharp.Tests/ArithmeticOperationTests.fs(29,9): error FS1109: A reference to the type 'System.Object' in assembly 'System.Runtime' was found, but the type could not be found in that assembly [/Users/travis/build/migueldeicaza/TensorFlowSharp/tests/TensorFlowSharp.Tests/TensorFlowSharp.Tests.fsproj]
  
/Users/travis/build/migueldeicaza/TensorFlowSharp/tests/TensorFlowSharp.Tests/ArithmeticOperationTests.fs(56,9): error FS1109: A reference to the type 'System.Object' in assembly 'System.Runtime' was found, but the type could not be found in that assembly [/Users/travis/build/migueldeicaza/TensorFlowSharp/tests/TensorFlowSharp.Tests/TensorFlowSharp.Tests.fsproj]
```

**Comment by Dorokhov** [comment]
Hi @migueldeicaza , build is success on Travis, but the tests fail with the error "System.TypeLoadException : Could not resolve type with token 01000032 (from typeref, class/assembly System.Numerics.Complex, netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)"

I found the same bug here https://github.com/mono/mono/issues/6339
and it sounds like the known mono bug to me.

Do the tests (F#, C#) work on your local machine?

**Comment by migueldeicaza** [comment]
Progress!   Ok, I can reproduce that locally.

Good lord, what are those millions of assemblies doing in my directory.  What in the world is this mess?

**Comment by migueldeicaza** [comment]
HOLY MOLLY.   EACH SAMPLE NOW GOES FROM HAVING 2 ASSEMBLIES TO 99. 

What is this hell scenario I have walked into.

**Comment by migueldeicaza** [comment]
giphy

**Comment by migueldeicaza** [comment]
This is not good.

First, I could probably debug this, but this is just a colossal mess to begin with.

Perhaps what I could do is just package the NuGet manually and add Xamarin.Mac and .NET Core payloads, that on its own sounds like a world of pain, but it is peanuts compared to this.

**Comment by migueldeicaza** [comment]
Further research: I find that if I remove "netstandard.dll" from the output directory, and let Mono do its job, it will work correctly.   The question to figure out is what is copying all this junk into my directory in the first place.    We should let the runtime go and resolve this netstandard.dll from wherever it is appropriate.

**Comment by migueldeicaza** [comment]
Ok more data:  Peter from the .net gave me a trick to eliminate all the assembly spam, need to upgrade the .net framework project versionto 4.7.2.   Will try tomorrow

**Comment by migueldeicaza** [comment]
Update: we are going to need a new release of Mono to get a fix for the `System.Numerics` mapping, otherwise switching to .NET Standard would stop working on Mono (for complex numbers).

This is the Mono commit required: e70439f1868fc29e5b649c89222829f02fc886d3

**Comment by migueldeicaza** [comment]
Landed Matthew's patch on master instead.

**Pull request closed without merging**
