### PR TITLE
Move to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by Dorokhov**
- transformed project either to netcoreapp2.0 or netstandard2.0
- dotnet runtime version is 2.0.3
- fixed test running on travis by using dotnet CLI

### CODE REVIEW

**Comment by migueldeicaza** [comment]
While I do want to .NET standard 2 for the library, I do not want to move the project to netcoreapp, among other reasons, because I am using Mono to develop this at home.

**Comment by rdthompson2020** [comment]
@migueldeicaza Unless I'm missing something, it's great that you're using Mono. With Unity Tech. hiring AAA engineers Mike Acton and Andreas Fredriksson; TensorFlow via TensorFlowSharp inside Unity3D is going to be the best option for simulation and options for AR, VR and much (much) more via TensorFlow Serving (of models).

**Comment by rdthompson2020** [comment]
@migueldeicaza Although .NET Standard 2 (spec standard for set of APIs for all libraries) sounds great, ultimately my hope is that your library fully supports TensorFlow inside Unity3D officially.

**Comment by migueldeicaza** [comment]
Landed an alternative version from Matthew to Master.

**Pull request closed without merging**
