### PR TITLE
Appveyor CI (#1)

### PR DESCRIPTION
**Pull request by hanabi1224**

### CODE REVIEW

**Comment by hanabi1224** [comment]
@migueldeicaza  In this PR I have converted all csproj sfproj to netcore syntax , added appveyor ci and cleanedup travis ci a little bit, please let me know your concerns

**Comment by hanabi1224** [comment]
@migueldeicaza  Kindly ping on this

**Comment by migueldeicaza** [comment]
It is hard to understand what is going on here, or why would I want to merge these changes.  Can you explain?

**Comment by hanabi1224** [comment]
@migueldeicaza  this PR adds appveyor CI support, converts all csproj / sfproj from legacy format to latest, also fixes example projects that does not run out of box without manually copying native libs around

**Comment by migueldeicaza** [comment]
Let us split this in pieces, as I stated somewhere else, I mostly work on VSMac with Mono in .NET Framework mode, so until those two get full support for this, I wont convert the format of the csproj/fsproj.

**Comment by migueldeicaza** [comment]
This PR contains too many unrelated things:

* A new dependency on a third party NuGet
* Some version checking/debugging (?)
* Switches the .travis.yml file to run the tests with .NET Core from Mono
* Migration to a new file format, which I am not sure works with VSMac and Mono, this would have to be tested.
* Changes to the F# tests to not rely on some /tmp file, this looks like a good idea in principle

I do not know much about AppVeyor, is the idea that this runs tests on Windows in addition to the tests I am running on Mac with Travis?

There are merits to different changes, but I cant take a grab bag of changes like this.

**Comment by SimantoR** [comment]
There are definitely some good changes here. But some unrelated changes as well. Maybe we can clean up this PR and take what makes sense?

**Comment by migueldeicaza** [comment]
Yes, we should isolate those changes.

**Pull request closed without merging**
