### PR TITLE
#123 add list devices. 

### PR DESCRIPTION
**Pull request by alexpantyukhin**
Added `ListDevices` functionality. Need to fix TF_DeleteDeviceList.

### CODE REVIEW

**Comment by migueldeicaza** [comment]
This introduces a new idiom for handling exceptions - I am not sure why I would want that.

**Comment by alexpantyukhin** [comment]
I got it from there: https://github.com/tensorflow/tensorflow/blob/b474e55c23e5cc42b01a1ddea34751f01110deb6/tensorflow/python/framework/errors_impl.py#L460  . Maybe it would be okay to have just function MakeSpecificException after each call of state-functions. 
Specific exeption are implmented in the https://github.com/migueldeicaza/TensorFlowSharp/pull/173 PR.

**Comment by migueldeicaza** [comment]
TensorFlowSharp uses a different idiom for this, I do not want to introduce a different way of raising exceptions.    There is a second problem with this, the existing idiom has a way of handling nested operations, and this does not take care of this either.

I can manually merge the other parts of the change, but the history would be attributed by me, or you can submit a new version of the patch with just the new functionality added (ListDevices) using the existing idioms in the binding and I can merge it.

**Comment by alexpantyukhin** [comment]
I will make a commit which fixes exceptions idioms.

**Comment by alexpantyukhin** [comment]
done

**Comment by migueldeicaza** [comment]
Thank you for changing the code!

**Pull request merged**
