### PR TITLE
Add preview ARM support in TensorFlowSharp using arm32/arm64

### PR DESCRIPTION
**Pull request by jessebenson**
- Remove 64-bit checks from code to support this.
- Add linux-arm/linux-arm64 specific binaries of libtensorflow.so/libtensorflow_framework.so to the Nuget package.

See this repo for instructions on cross-compiling Tensorflow for arm from source:
https://github.com/jessebenson/tensorflow-on-arm

### CODE REVIEW

**Comment by jessebenson** [comment]
The CI build failed because I changed the paths where native libs are installed to with this change:

/usr/local/share/dotnet/sdk/2.1.4/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(204,5): error : Could not find a part of the path '/Users/travis/build/migueldeicaza/TensorFlowSharp/native/win7-x64'. [/Users/travis/build/migueldeicaza/TensorFlowSharp/TensorFlowSharp/TensorFlowSharp.csproj]

**Comment by nrandell** [comment]
What's the status of this? I'm currently trying to get the raspberry working. I've got this working on a fork, happy to submit a pull request for this.

**Comment by jessebenson** [comment]
FYI - I've published TensorFlowSharp.ARM as a nuget package that can be included in a .NET Core application to be run on ARM:
https://www.nuget.org/packages/TensorFlowSharp.ARM

**Comment by nrandell** [comment]
@jessebenson  - that's quite an old version isn't it?

**Comment by migueldeicaza** [comment]
Good as a reference, generally, I would like to get the

**Pull request closed without merging**
