### PR TITLE
[WIP] Support Mobile(Android)

### PR DESCRIPTION
**Pull request by yamachu**
~~If netstd2.0 support will be merged, I'll remove netstd suppport commit in this PR.~~
I'll remove netstd support commit.

WIP

- [ ] Check load bundle model file
~~- [ ] Support iOS~~ Oops...it's difficult for me...

Notice:

If we run sample project on Android, it will crash. (`No OpKernel was registered to support Op ...`)

### CODE REVIEW

**Comment by migueldeicaza** [comment]
I suspect that we might want to bind fewer items for Android, as not the entire API surface is availble there, I will look into that.

**Comment by yamachu** [comment]
Yes, I think that we should support fewer API like TensorFlowLite.
But now TensorFlowLite has no C-API...

**Comment by xiaomaogy** [comment]
@migueldeicaza @yamachu Does this work only for Tensorflow 1.4 or also available for Tensorflow 1.5 or 1.6 with certain modification?

**Comment by migueldeicaza** [comment]
It is unclear to me if TensorFlowSharp as-is should be used in Android, perhaps we need TensorFlowLite instead for that.

**Comment by migueldeicaza** [comment]
Caveat: for mobile apps purely doing inference that might be the case, for larger android apps (say on ChromeOS), it might make sense to support full TensorFlowSharp, and the issue is whether we should ship the payload for those, as we would need to ship 4 native libraries, perhaps an add-on "TensroFlowSharp.Android" that brings the native libraries is the right approach.

**Pull request closed without merging**
