### PR TITLE
Remove unnecessary System.ValueTuple package dependency from netstandard2.0 target

### PR DESCRIPTION
**Pull request by hanabi1224**

### CODE REVIEW

**Comment by hanabi1224** [comment]
@migueldeicaza I'd like to remove System.ValueTuple package dependency for netstandard2.0 and net47 to make it cleaner, plz let me know your concerns, thanks!

**Comment by hanabi1224** [comment]
@migueldeicaza  Kindly ping on this

**Comment by migueldeicaza** [comment]
I do not undersatnd the need for this change, please explain

**Comment by hanabi1224** [comment]
@migueldeicaza  Generally it's good practise to only add dependencies when necessary, in this case System.ValueTupe package is only required for net46 target, so I removed it from netstandard and net47, does that make sense

**Comment by migueldeicaza** [comment]
Ok that part makes sense (the third file), but I do not understand the project format change in the first file, that looks unrelated.

**Comment by hanabi1224** [comment]
@migueldeicaza  That is to fix the issue that those example projects do not run out of box,

**Comment by migueldeicaza** [comment]
Can you describe where it does not run?    They run for me, and they run on CI, and would like to get to the bottom of this.   Is this on Windows, or with .NET Core on Unix?

**Comment by hanabi1224** [comment]
@migueldeicaza The project does not have any build script to copy native libtensorflow, how can it run out of box?

**Comment by hanabi1224** [comment]
@migueldeicaza  Also none of unittests run out of box,  you are using a hacky copy in your CI script below but people who run it locally will need to copy them manually, which is super inconvenient. 

- cp -R $TRAVIS_BUILD_DIR/native/*.dylib $TRAVIS_BUILD_DIR/tests/TensorFlowSharp.Tests/bin/Release/
  - cp -R $TRAVIS_BUILD_DIR/native/*.dylib $TRAVIS_BUILD_DIR/tests/TensorFlowSharp.Tests.CSharp/bin/Release/

**Comment by Andy-Wilkinson** [comment]
On a related note... Have you considered implementing a build automation system @migueldeicaza? I have had good experiences with Cake in the past (www.cakebuild.net, cross-platform, C# based, .NET Foundations). Would provide consistent repateble builds/unit-testing/packaging across local and CI. Maybe a bit heavyweight for now, but is simple enough to do if you wanted.

**Comment by SimantoR** [comment]
I defintiely agree with @hanabi1224 on this. The new _csproj_ format is definitely more modern approach. And adding the dependency instructions in the csproj as post-build instruction would make the dotnet cli and only build tool required to make something that works out of the box.
@migueldeicaza

**Comment by migueldeicaza** [comment]
It is correct that currently this expects the payload to be installed, the .travis.yml file shows how to do this. 

If someone wants to address how to install that, it can be done elsewhere, the changes in this pull request are not solving the root cause.

**Pull request closed without merging**
